# Generated by Django 3.2.16 on 2023-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient_amount_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
