# Generated by Django 3.2.16 on 2023-12-17 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231211_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.ManyToManyField(related_name='_users_user_is_subscribed_+', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
